### ISSUE TITLE
detection speed

### ISSUE THREAD

**Issue by kingvision** [raoqiyu/FaceDetection#1]
hi:
  raoqiyu
 thanks you for your code. i have a question , how much does it cost detecting a 640*480 image?
thanks

**Comment by raoqiyu** [comment]
HI:
kingvision,
detection speed of my code is slow. I just impletement a basic program, and i do not do any optimization.
To answer you question, i detection a image of size 640*480.
There are two ways to detect, scale image and scale template.
1 scale image: 3553.5347 msec
2 scan template : 1214.3355 msec
Thanks.
![1 image_3553_5347msec](https://cloud.githubusercontent.com/assets/4653325/10861184/da490338-7fb2-11e5-8241-57a0e2277cbe.png)
![2 template_1214_3355_msec](https://cloud.githubusercontent.com/assets/4653325/10861185/da4b1312-7fb2-11e5-97b7-5ee59f7dca3f.png)
